# Generated by Django 6.0.2 on 2026-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myConfigs', '0002_remove_doctor_email_remove_doctor_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
